# Generated by Django 5.0.3 on 2025-01-01 08:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="is_completed",
            new_name="completed",
        ),
        migrations.RemoveField(
            model_name="task",
            name="category",
        ),
        migrations.RemoveField(
            model_name="task",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="task",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="task",
            name="user",
        ),
    ]
